Add Data & DataUser Feature
billiyagi/Hanover-attendance pull request #12
Opened 2023-06-30 17:50 UTC by Amrasykr

Menambahkan Crud untuk table data dan data_user dengan tambahan modal dan pagination

2023-07-01 04:03 UTC, billiyagi commented on app/Http/Controllers/Admin/DashboardController.php
> +    public function member()
@Amrasykr pake Eloquient aja buat join tabelnya kaya yg di attendance, biar sama

2023-07-01 04:03 UTC, billiyagi commented on app/Http/Controllers/Admin/DataController.php
> +    public function index(Data $data)
Paginationnya kasih OrderBy

2023-07-01 07:26 UTC, billiyagi requested changes
Selesaikan Revisi nya ya...

2023-07-01 07:26 UTC, billiyagi commented on app/Http/Controllers/Admin/DataUserController.php
> +        $users = User::whereIn('id', function ($query) use ($dataId) {
Ini juga sama mar, ambil data user_id yg berelasi sma data_id di tabel data user pake eloquent aja

2023-07-01 07:26 UTC, billiyagi commented on app/Http/Middleware/Admin.php
> +            // return redirect()->route('member-dashboard');
Ini Middleware Admin jgn di komentar

2023-07-01 07:26 UTC, billiyagi commented on app/Http/Controllers/Admin/DashboardController.php
> +    public function member()
@Amrasykr pake Eloquient aja buat join tabelnya kaya yg di attendance, biar sama

2023-07-01 07:26 UTC, billiyagi commented on app/Http/Controllers/Admin/DataController.php
> +    public function index(Data $data)
Paginationnya kasih OrderBy

2023-07-01 07:26 UTC, billiyagi commented on database/migrations/2023_06_23_162613_create_users_relation_roles.php
>          Schema::dropIfExists('users_relation_roles');
ini semicolonnya hapus aja, setelah bracket ga perlu semicolon

2023-07-01 07:26 UTC, billiyagi commented on database/migrations/2023_06_26_132140_create_data_user.php
> +                ->references('id')->on('users')
Ini Relationnya dipisah, jdi beberapa file

2023-07-01 07:26 UTC, billiyagi commented on database/migrations/2023_06_26_133611_create_data_user_relation_data.php
ini harusnya dipake ya

2023-07-01 07:26 UTC, billiyagi commented on database/migrations/2023_06_26_133620_create_data_user_relation_users.php
ini harusnya dipake ya

2023-07-01 07:26 UTC, billiyagi commented on resources/views/admin/dataUser/edit.blade.php
> +                <form action="{{url('admin/dataUser/'.$data->id.'/update')}}" method="POST" enctype="multypart/form-data">
form actionya langsung string aja ga perlu pake function url

2023-07-01 07:26 UTC, billiyagi commented on resources/views/layouts/footer/footer-admin.blade.php
> +  <form class="modal-box" action="{{url('admin/data/store')}}" method="POST" enctype="multypart/form-data">
actionnya langsung string aja ga perlu pake function url

2023-07-01 07:26 UTC, billiyagi commented on routes/web.php
> +            Route::get('/dataUser/{dataId}/create', [DataUserController::class, 'create'])->name('createDataUser');
ini ga perlu pake route name

2023-07-01 07:26 UTC, billiyagi commented on app/Http/Controllers/Admin/DataController.php
> +        return redirect()->route('createDataUser', ['dataId' => $dataId]);
redirect langsung aja ke url ga perlu pakai route

2023-07-01 07:46 UTC, Amrasykr commented on app/Http/Controllers/Admin/DashboardController.php
> +    public function member()
ngg ada yang pake join bil emng dimananya

2023-07-01 16:00 UTC, billiyagi requested changes

2023-07-01 16:00 UTC, billiyagi commented on app/Http/Controllers/Admin/DashboardController.php
> +    public function member()
> ngg ada yang pake join bil emng dimananya

ini di dashboard controller ada join di line 25 method member

2023-07-02 12:09 UTC, billiyagi approved these changes
Semua sudah OK!

2023-07-02 12:10 UTC, billiyagi commented
Good Job @Amrasykr

2023-07-02 12:10 UTC, merged